### PR TITLE
initial pr for waveform ui

### PR DESCRIPTION
**Pull request by jacgrady1**
@fuermosi777 need help

### CODE REVIEW

**Comment by jacgrady1** [comment]
http://tftsandbox.oss-cn-shanghai.aliyuncs.com/polly_speeches/answer-389.mp3 might need some music for reference.

**Comment by jacgrady1** [comment]
No it does not.

**Comment by fuermosi777** [comment]
Let me pick your commit and see what I can do

**Comment by fuermosi777** [comment]
It says "No 'Access-Control-Allow-Origin' header is present on the requested resource." 

Need to update OSS setups

**Pull request closed without merging**
